spring:
  h2:
    console:
      enabled: true
  shell:  #disable spring shell so that ApplicationStartedEvent gets fired
    interactive:
      enabled: false

offers:
  page:
    size: 5

#logging.level:
#  root: INFO
#  org.springframework.security: TRACE